// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "identity provider": idp Resource Client
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/identity-provider/design
// --out=$(GOPATH)/src/github.com/JormungandrK/identity-provider
// --version=v1.2.0-dirty

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetGoogleMetadataIdpPath computes a request path to the getGoogleMetadata action of idp.
func GetGoogleMetadataIdpPath() string {

	return fmt.Sprintf("/saml/idp/metadata/google")
}

// Get Google's metadata
func (c *Client) GetGoogleMetadataIdp(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetGoogleMetadataIdpRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetGoogleMetadataIdpRequest create the request corresponding to the getGoogleMetadata action endpoint of the idp resource.
func (c *Client) NewGetGoogleMetadataIdpRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
