// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "identity provider": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/identity-provider/design
// --out=$(GOPATH)/src/github.com/JormungandrK/identity-provider
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// GetGoogleMetadataIdpContext provides the idp getGoogleMetadata action context.
type GetGoogleMetadataIdpContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewGetGoogleMetadataIdpContext parses the incoming request URL and body, performs validations and creates the
// context used by the idp controller getGoogleMetadata action.
func NewGetGoogleMetadataIdpContext(ctx context.Context, r *http.Request, service *goa.Service) (*GetGoogleMetadataIdpContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := GetGoogleMetadataIdpContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *GetGoogleMetadataIdpContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
