// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "identity provider": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/Microkubes/identity-provider/design
// --out=$(GOPATH)/src/github.com/Microkubes/identity-provider
// --version=v1.3.1

package app
