// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "identity provider": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/identity-provider/design
// --out=$(GOPATH)/src/github.com/JormungandrK/identity-provider
// --version=v1.2.0-dirty

package test
